import Head from 'next/head'
import Homebanner from '../components/Homebanner'
export default function Home() {
  return (
    <div>
      <Head>
        <title>Paradise Store- the global store cofort.</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>

        {/* Home Content Here */}
        {/* home banner */}
        <Homebanner />
        {/* feature section */}
        {/* home products */}
        {/* offer section */}
        {/* summery */}
      </main>
    </div>
  )
}
