import Head from 'next/head'
import About from './about'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Paradise Store- the global store cofort.</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
    </div>
  )
}
