import Head from 'next/head'
export default function Home() {
  return (
    <div>
      <Head>
        <title>Paradise Store- the global store cofort.</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className='h-screen'>

      </div>
      Home Content Here
      {/* home banner */}
      {/* feature section */}
      {/* home products */}
      {/* offer section */}
      {/* summery */}
    </div>
  )
}
